# Site settings
title: AirGateway # - Disrupting the airline distribution
head-title: AirGateway - Enabling the NDC age for the airline distribution industry
company: AirGateway GmbH
email: contact@airgateway.com
url: https://airgateway.com
description: "Enabling the NDC age for the airline distribution industry. We're a technical partner for travel agents (OTAs, TMCs, Tour-operators, and Consolidators) facilitating them the access to the new IATA's NDC (New Distribution Capability) standard"
footer: AirGateway GmbH.
blog-title: AirGateway News

# Tracking Services
google_analytics: "UA-77281199-1"

# Build settings
excerpt_separator: <!--more-->
markdown: kramdown
permalink: /blog/:categories/:title.html
include:
  - _redirects

# SASS
sass:
  style: compressed

# Plugins

#gems:
#- jekyll-admin

### Contents ###

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AirGateway
  - title: github
    url: https://github.com/AirGateway
  - title: linkedin
    url: https://linkedin.com/company/AirGateway

# Products
# products:
#   - name: "NDC Aggregation Gateway"
#     desc: "Our NDC Gateway aggregator enables OTAs, TMCs, Tour-Operators, or Consolidators to adopt the NDC standard in a seamless way while saving development costs and times."
#     icon: i-agw-airplane-o
#     features:
#       - "NDC-aligned full real-time aggregation"
#       - "NDC implementation & version agnostic"
#       - "Full NDC capabilities: Shopping, Booking, Servicing, Ticketing"
#       - "Anonymous and Personalised Shopping, Private/Public/Corporate Fares"
#       - "Ancilliaries support and normalization"
#   - name: "NDC Analytics Tool"
#     desc: "Our NDC Analytics suite provides a better view and understanding on your NDC Channel. It's flexible and customizable to track any relevant KPI for your business through your live NDC channel."
#     icon: i-agw-graph-o
#     features:
#       - "NDC-aware performance analytics"
#       - "Technical and Business relevant KPIs"
#       - "Customizable KPIs for your business"
#       - "Customizable outcoming charts, dashboards, and reports"
#   - name: NDC Monitor Tool
#     desc: A service monitor 24/7 to your NDC channel observing its performance and raising alerts when indicators go out of range.
#     icon: i-agw-radar-o
#     features:
#       - "NDC-aware KPIs"
#       - "Technical and Business relevant indicators"
#       - "Customizable indicators and ranges"
#       - "API for 3rd party systems integration"

# Airlines
# airlines:
#   - image: british-airways
#     name: British Airways
#     date: 01-Sep-2016
#   - image: american-airlines
#     name: American Airlines
#     date: 20-Sep-2016
#   - image: s7-airlines
#     name: Siberian Airlines
#     date: 20-Nov-2016
#   - image: emirates
#     name: Emirates
#     date: 01-Feb-2017
#   - image: iberia
#     name: Iberia Líneas Aéreas de España
#     date: 01-Mar-2017
#   - image: westjet-airlines
#     name: WestJet Airlines
#     date: 15-Mar-2017
#   - image: lufthansa
#     name: Lufthansa
#     date: 22-Aug-2017
#   - image: swiss
#     name: Swiss
#     date: 22-Aug-2017
#   - image: austrian-airlines
#     name: Austrian Airlines
#     date: 22-Aug-2017
#   - image: brussels-airlines
#     name: Brussels Airlines
#     date: 22-Aug-2017

# About
# updates:
#   - date: April 2016
#     heading: AirGateway is founded
#     text: We are building our NDC Gateway, a full NDC-compliant real-time aggregation technology.
#   - date: June 2016
#     heading: Connected to BA
#     text: We are glad to announce we have already enabled British Airways NDC API.
#     link: /blog/airlines/connected-to-ba.html
#   - date: August 2016
#     heading: AERTiCKET to use our NDC Gateway Aggregation
#     text: AERTiCKET, the biggest air-travel retailer in Germany, will be integrating with our NDC Gateway.
#     link: /blog/agreements/aerticket-to-use-our-ndc-gateway-aggregation.html
#   - date: January 2017
#     heading: AirGateway selected to exhibit in the Travel Technology Europe Launchpad
#     text: We have been selected as launchpad exhibitors in the most popular event in Europe introducing disrupting technologies for the travel industry.
#     link: /blog/events/airgateway-selected-to-exhibit-in-the-travel-technology-europe-launchpad.html
#   - date: March 2017
#     heading: AirGateway inks agreement with SITA to collaborate on creating NDC-related products
#     text: We will be partnering with SITA to create a family of NDC products for the airline industry
#     link: /blog/agreements/airgateway-and-sita-to-partner-building-ndc-products-for-the-airline-industry.html
#     date: March 2017
#   - heading: Lufthansa Group added to our NDC aggregation platform
#     text: Lufthansa, Swiss, Austrian Airlines, and Brussels Airlines are now among the airlines available in our NDC platform for travel agents to connect to
#     date: June 2017



#
# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210
#

# Build settings
# markdown: kramdown
# permalink: pretty

collections:
  airlines:
    output: false
