# Site settings
title: AirGateway # - Disrupting the air travel distribution
head-title: AirGateway -- Enabling the NDC age for the air travel industry
company: AirGateway GmbH i.G.
email: contact@airgateway.net
url: http://airgateway.net
description: "Enabling the NDC age for the air travel industry. We are basing our services on enabling the IATA's NDC (New Distribution Capability) standard for air-travel related companies."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: D60004
  # secondary: D60024
  secondary-dark: 333
  primary-clear: '#fff'
  header-dark: '#D60004'
  main-text: '#000'
  links: '#D60004'

# Footer settings
footer: AirGateway GmbH. i.G.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AirGtwy
  - title: github
    url: https://github.com/AirGateway
  - title: angellist
    url: https://angel.co/airgateway


# Build settings
markdown: kramdown
permalink: pretty


# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

#
# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210
#
# # Build settings
# markdown: kramdown
# permalink: pretty
