# Site settings
title: AirGateway # - Disrupting the airline distribution
head-title: AirGateway - Enabling the NDC age for the airline distribution industry
company: AirGateway GmbH
email: contact@airgateway.com
url: https://airgateway.com
description: "Enabling the NDC age for the airline distribution industry. We're a technical partner for travel agents (OTAs, TMCs, Tour-operators, and Consolidators) facilitating them the access to the new IATA's NDC (New Distribution Capability) standard"
footer: AirGateway GmbH.
blog-title: AirGateway News

# Tracking Services
google_analytics: "UA-77281199-1"

# Build settings
excerpt_separator: <!--more-->
markdown: kramdown
permalink: /blog/:categories/:title.html
include:
  - _redirects

# SASS
sass:
  style: compressed

# Plugins

#gems:
#- jekyll-admin

### Contents ###

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AirGateway
  - title: github
    url: https://github.com/AirGateway
  - title: linkedin
    url: https://linkedin.com/company/AirGateway


# # Postal address (add as many lines as necessary)
# address:
#   - line: Gutzkowkstr. 8
#   - line: Berlin 10827, Germany
#

# Build settings
# markdown: kramdown
# permalink: pretty

collections:
  airlines:
    output: false
  providers:
    output: false
  customers:
    output: false