# Site settings
title: AirGateway # - Disrupting the air travel distribution
head-title: AirGateway - Enabling the NDC age for the air-travel distribution industry
company: AirGateway GmbH
email: contact@airgateway.net
url: http://airgateway.net
description: "Enabling the NDC age for the air travel retail industry. We are basing our services on enabling the IATA's NDC (New Distribution Capability) standard for air-travel related companies."
footer: AirGateway GmbH.
blog-title: AirGtwy Blog

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: D60004
  # secondary: D60024
  secondary-dark: 333
  primary-clear: '#fff'
  header-dark: '#D60004'
  main-text: '#000'
  links: '#D60004'

# Tracking Services
google_analytics: "UA-77281199-1"

# Build settings
excerpt_separator: <!--more-->
markdown: kramdown
permalink: /blog/:categories/:title.html

### Contents ###

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AirGtwy
  - title: github
    url: https://github.com/AirGateway
  - title: angellist
    url: https://angel.co/airgateway

# Services
services:
  - name: NDC Gateway
    desc: Our NDC Gateway aggregator enables OTAs, TMCs or Fare Consolidators to adopt the NDC standard seamless, faster, at a lower costs.
    icon: fa-connectdevelop
    features:
      - NDC-compliant real-time aggregation
      - Anonymous/Personalised Shopping
      - NDC implementations isolation (SOAP, REST)
      - Authentication methods isolation
      - Ancilliaries Normalization between airlines
  - name: NDC Analytics
    desc: Our NDC Analytics suite provides a better view and understanding on your NDC Channel. It's flexible and customizable to track any data on your NDC channel.
    icon: fa-bar-chart
    features:
      - NDC-focused analytics
      - Technical and Business relevant KPIs
      - Customisable KPI's
      - Customisable display and dashboards
  - name: NDC Monitor
    desc: A service to monitor 24/7 your NDC channel observing performance and raising alerts when indicators go out of range.
    icon: fa-video-camera
    features:
      - NDC-focused indicators
      - Technical and Business relevant indicators
      - Customisable indicators and ranges
      - API for 3rd party systems integration

# About
updates:
  - icon: AirGatewayLogo.png
    date: April 2016
    heading: AirGateway is founded
    text: We are building our NDC Gateway, a full NDC-compliant real-time aggregation technology.
  - icon: airline.jpg
    date: June 2016
    heading: Connected to BA
    text: We glad to announce we have already enabled British Airways's NDC service (level 3 certification).
    link: /blog/airlines/connected-to-ba.html
  - icon: handshake.jpg
    date: August 2016
    heading: AERTiCKET to use our NDC Gateway Aggregation
    text: AERTiCKET, the biggest air-travel retailer in Germany, will be integrating with our NDC Gateway.
    link: /blog/agreements/aerticket-to-use-our-ndc-gateway-aggregation.html
  - icon: conference.jpg
    date: January 2017
    heading: AirGateway selected to exhibit in the Travel Technology Europe Launchpad
    text: We have been selected as launchpad exhibitors in the most popular event in Europe introducing disrupting technologies for the travel industry.
    link: /blog/events/airgateway-selected-to-exhibit-in-the-travel-technology-europe-launchpad.html


#
# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210
#

# Build settings
# markdown: kramdown
# permalink: pretty
