products:
  - desc: >-
      Our NDC Gateway aggregator enables OTAs, TMCs, Tour-Operators, or
      Consolidators to adopt the NDC standard in a seamless way while saving
      development costs and times.
    features:
      - NDC-aligned full real-time aggregation
      - NDC implementation & version agnostic
      - 'Full NDC capabilities: Shopping, Booking, Servicing, Ticketing'
      - 'Anonymous and Personalised Shopping, Private/Public/Corporate Fares'
      - Ancilliaries support and normalization
    icon: i-agw-airplane-o
    name: NDC Aggregation Gateway
  - desc: >-
      Our NDC Analytics suite provides a better view and understanding on your
      NDC Channel. It's flexible and customizable to track any relevant KPI for
      your business through your live NDC channel.
    features:
      - NDC-aware performance analytics
      - Technical and Business relevant KPIs
      - Customizable KPIs for your business
      - 'Customizable outcoming charts, dashboards, and reports'
    icon: i-agw-graph-o
    name: NDC Analytics Tool
  - desc: >-
      A service monitor 24/7 to your NDC channel observing its performance and
      raising alerts when indicators go out of range
    features:
      - NDC-aware KPIs
      - Technical and Business relevant indicators
      - Customizable indicators and ranges
      - API for 3rd party systems integration
    icon: i-agw-radar-o
    name: NDC Monitor Tool
