# Products
products:
  - name: "test"
    desc: "test."
    icon: test.png
    features:
      - "test"
      - "test2"
  - name: "new"
    desc: "new test."
    icon: newtest.png
    features:
      - "newtest"
      - "newtest2"
  - name: "NDC Analytics Tool"
    desc: "Our NDC Analytics suite provides a better view and understanding on your NDC Channel. It's flexible and customizable to track any relevant KPI for your business through your live NDC channel."
    icon: i-agw-graph-o
    features:
      - "NDC-aware performance analytics"
      - "Technical and Business relevant KPIs"
      - "Customizable KPIs for your business"
      - "Customizable outcoming charts, dashboards, and reports"
  - name: NDC Monitor Tool
    desc: A service monitor 24/7 to your NDC channel observing its performance and raising alerts when indicators go out of range.
    icon: i-agw-radar-o
    features:
      - "NDC-aware KPIs"
      - "Technical and Business relevant indicators"
      - "Customizable indicators and ranges"
      - "API for 3rd party systems integration"
